<section class="loc-page" itemscope itemtype="http://schema.org/Place">
  <div class="loc-page-data"><?php echo $this->getChildHtml('info') ?></div>  
  <div class="loc-page-map-wrap"><?php echo $this->getChildHtml('map') ?></div>
  <div class="loc-page-additional"><?php echo $this->getChildHtml('attributes') ?></div>
</section>

<section class="loc-nearby">
  <?php echo $this->getChildHtml('others') ?>
</section>
