<section class="block block-locator">
  <header class="block-title">
    <h3>Find a Store</h3>
  </header>
  <div class="block-content">
    <form id='locator-search' action="<?php echo Mage::getURL('') ?>locator/search/">
      <input name="s" type="text" class="input-text required-entry" placeholder="<?php echo $this->__('Enter a postcode or suburb') ?>" />
      <button class="btn" type="submit">Go</button>
    </form>
  </div>
</section>
