<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=<?php echo Mage::getStoreConfig('locator_settings/google_maps/api_key'); ?>&sensor=false&libraries=places"></script>
<script>

document.observe("dom:loaded", function() {
  
   //Locator.settings.maxZoom = 16;
<?php
//  Uncomment this line to start customizing the look of the google map displayed
//    Locator.settings.theme = [
//        {
//            featureType: "road",
//            elementType: "geometry",
//            stylers: [
//                { lightness: 100 },
//                { visibility: "simplified" }
//            ]
//        },{
//            featureType: "road",
//            elementType: "labels",
//            stylers: [
//                { visibility: "off" }
//            ]
//        }
//    ];
?>

    //initLocator();
});

</script>
