<?php
/**
 * Location extension for Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013 Andrew Kett. (http://www.andrewkett.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
  $locations = $this->getLocations()->getItems();
?>
<?php if($locations): ?>
    <?php if(count($locations) > 0): ?>
        <h2>Locations</h2>
        <ul class="locations">
        <?php
            $i = 0;
            foreach($locations as $location):
                $i++;
        ?>
            <li class="location-info">
                <article itemscope itemtype="http://data-vocabulary.org/Place" class="loc loc-teaser" data-id="<?php echo $location->getId(); ?>">
                    <h3 itemprop="name"><?php echo $location->getTitle(); ?></h3>
                    <address itemprop="address"><?php echo $location->getAddress() ?></address>
                    <a itemprop="url" href="<?php echo $location->getUrl(); ?>">View More</a> | <a href="<?php echo $location->getDirectionsLink(); ?>" target="_blank">Get Directions</a>
                </article>
            </li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
<?php else: ?>
  No results found
<?php endif; ?>

