<script type="text/javascript">
  document.observe("dom:loaded", function() {
    mapJson = '<?php echo $this->getLocations()->toJson(); ?>';
    Locator.locations = parseLocationsJson(mapJson);
    Locator.settings.country_code = "<?php echo Mage::getStoreConfig("locator_settings/search/country_code"); ?>";
    Locator.settings.useAutocomplete = <?php echo Mage::getStoreConfig("locator_settings/search/use_places_autocomplete"); ?>;
    initSearchPage();

    if(Locator.settings.useAutocomplete){
        initializeAutocomplete();
    }
    
  });
</script>
